export {
  RiSearchLine,
  RiNotificationLine,
  RiUserAddLine,
  RiDashboardLine,
  RiContactsLine,
  RiInputMethodLine,
  RiGitMergeLine,
  RiAddLine,
  RiPencilLine,
  RiMenuLine,
  RiCloseLine,
  RiBankLine,
  RiHomeGearLine,
  RiBookReadLine,
  RiBook3Line,
  RiDraftLine,
  RiFileUserLine,
} from 'react-icons/ri'
